// Code generated by "stringer -type Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Whitespace-2]
	_ = x[Comment-3]
	_ = x[Keyword-4]
	_ = x[Ident-5]
	_ = x[String-6]
	_ = x[symbolStart-7]
	_ = x[Lparen-8]
	_ = x[Rparen-9]
	_ = x[Period-10]
	_ = x[Add-11]
	_ = x[Sub-12]
	_ = x[Mul-13]
	_ = x[Quo-14]
	_ = x[BitShl-15]
	_ = x[BitShr-16]
	_ = x[Eq-17]
	_ = x[Neq-18]
	_ = x[Lt-19]
	_ = x[Gt-20]
	_ = x[Leq-21]
	_ = x[Geq-22]
	_ = x[NullEqual-23]
	_ = x[Not-24]
	_ = x[Comma-25]
	_ = x[Semicolon-26]
	_ = x[symbolEnd-27]
}

const _Type_name = "IllegalEOFWhitespaceCommentKeywordIdentStringsymbolStart().+-*/<<>>=!=<><=>=<=>!,;symbolEnd"

var _Type_index = [...]uint8{0, 7, 10, 20, 27, 34, 39, 45, 56, 57, 58, 59, 60, 61, 62, 63, 65, 67, 68, 70, 71, 72, 74, 76, 79, 80, 81, 82, 91}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
