// Code generated by "stringer -type Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Whitespace-2]
	_ = x[Comment-3]
	_ = x[Keyword-4]
	_ = x[Ident-5]
	_ = x[Quoted-6]
	_ = x[DataType-7]
	_ = x[String-8]
	_ = x[symbolStart-9]
	_ = x[Lparen-10]
	_ = x[Rparen-11]
	_ = x[Period-12]
	_ = x[Add-13]
	_ = x[Sub-14]
	_ = x[Mul-15]
	_ = x[Quo-16]
	_ = x[BitShl-17]
	_ = x[BitShr-18]
	_ = x[Eq-19]
	_ = x[Neq-20]
	_ = x[Lt-21]
	_ = x[Gt-22]
	_ = x[Leq-23]
	_ = x[Geq-24]
	_ = x[NullEqual-25]
	_ = x[Not-26]
	_ = x[Assign-27]
	_ = x[Comma-28]
	_ = x[Semicolon-29]
	_ = x[symbolEnd-30]
}

const _Type_name = "IllegalEOFWhitespaceCommentKeywordIdentQuotedDataTypeStringsymbolStart().+-*/<<>>=!=<><=>=<=>!:=,;symbolEnd"

var _Type_index = [...]uint8{0, 7, 10, 20, 27, 34, 39, 45, 53, 59, 70, 71, 72, 73, 74, 75, 76, 77, 79, 81, 82, 84, 85, 86, 88, 90, 93, 94, 96, 97, 98, 107}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
